INITIAL_BITCOIN_PRICE = 9193.99
DATE_COLUMN = 0
CHANGE_COLUMN = 9
OPEN_COLUMN = 5
CLOSE_COLUMN = 6

OUTPUT_PATH = "../models/sentiment-lstm/output/"

DECREASE = 0
INCREASE = 1

MESSAGE_DAILY_STATUS = 0
MESSAGE_RESULT = 1
MESSAGE_PROFIT = 2
MESSAGE_PERIOD = 3
MESSAGE_AVERAGE = 4
MESSAGE_COUNT = 5
MESSAGE_DEFAULT = 6
MESSAGE_AVG = 7